# Generated by Django 6.0.3 on 2026-03-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='phone',
        ),
        migrations.AddField(
            model_name='borrower',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo / En Pago'), ('PAID', 'Pagado'), ('OVERDUE', 'En Mora')], default='ACTIVE', help_text='Estado del préstamo', max_length=20)),
                ('term_months', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(help_text='Cliente de este préstamo', on_delete=django.db.models.deletion.CASCADE, to='api.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=200)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('OVERDUE', 'En Mora')], default='PENDING', max_length=10)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='api.loans')),
            ],
        ),
    ]
