# Generated by Django 6.0.3 on 2026-03-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_borrower_phone_borrower_note_loans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='borrower',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
