# Generated by Django 6.0.3 on 2026-03-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_borrower_name_borrower_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo / En Pago'), ('PAID', 'Pagado'), ('OVERDUE', 'En Mora')], default='ACTIVE', max_length=20),
        ),
    ]
