# Generated by Django 6.0.3 on 2026-03-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_loans_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
