# Generated by Django 6.0.3 on 2026-03-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_installment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loans',
            name='payment_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Mensual'), ('BIWEEKLY', 'Quincenal')], default='MONTHLY', max_length=20),
        ),
    ]
