# Generated by Django 6.0.3 on 2026-03-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_loans_interest_rate_loans_payment_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_goal', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
            ],
        ),
    ]
