# Generated by Django 5.1.4 on 2026-03-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
